import { Button } from '@/components/Elements';
import { Header, MainLayout } from '@/components/Layout';
import { authSlice, loginWithGithubCode } from '@/features/auth';
import { storage } from '@/utils/storage';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';

export default function GithubCallback() {
  const router = useRouter();
  const dispatch = useDispatch();
  const code = router.query.code;
  useEffect(() => {
    if (typeof code === 'string') {
      (async () => {
        const result = await loginWithGithubCode({ code });
        dispatch(
          authSlice.actions.setAuth({
            ...result.data,
          })
        );
        storage.setValue('accessToken', result.data.accessToken);
        storage.setValue('refreshToken', result.data.refreshToken);
        storage.setValue('userUuid', result.data.userUuid);
        router.push('/');
      })();
    }
  }, [router, code]);
  console.log(router);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header
          rightbuttons={
            <>
              <Link href="/auth/login">
                <Button>로그인</Button>
              </Link>
              <Link href="/auth/regist">
                <Button variant="primary" isoutlined={true}>
                  회원가입
                </Button>
              </Link>
            </>
          }
        />
        {/* <Inner>
          <Title>회원가입</Title>
          <JoinForm />
          <Guide>
            이미 계정이 있으신가요?
            <Link href="/auth/login">
              <Button
                justifycontent="center"
                isoutlined={true}
                border="none"
                size="large"
              >
                로그인하기
              </Button>
            </Link>
          </Guide>
        </Inner> */}
      </MainLayout>
    </>
  );
}
