import { Button } from '@/components/Elements';
import { Header, MainLayout } from '@/components/Layout';
import { GithubLoginButton, LoginForm } from '@/features/auth';
import Head from 'next/head';
import Link from 'next/link';
import { Guide, Inner, Title } from '@/styles/pageStyles/auth/login.style';
import { useDispatch, useSelector } from 'react-redux';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function Login() {
  const userUuid = useSelector(({ auth }) => auth.userUuid);
  const router = useRouter();

  useEffect(() => {
    if (userUuid) {
      router.replace('/');
    }
  }, [userUuid, router]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header />
        <Inner>
          <Title>로그인</Title>
          <LoginForm />
          <Guide>
            아직 계정이 없으신가요?
            <Link href="/auth/join">
              <Button
                justifycontent="center"
                isoutlined={true}
                border="none"
                size="large"
              >
                회원가입하기
              </Button>
            </Link>
          </Guide>
          <GithubLoginButton />
        </Inner>
      </MainLayout>
    </>
  );
}
