import { Button } from '@/components/Elements';
import { Header, MainLayout } from '@/components/Layout';
import { RegistForm } from '@/features/auth';
import Head from 'next/head';
import Link from 'next/link';
import { Guide, Inner, Title } from './regist.style';

export default function Regist() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header
          rightbuttons={
            <>
              <Link href="/auth/login">
                <Button>로그인</Button>
              </Link>
              <Link href="/auth/regist">
                <Button variant="primary" isoutlined={true}>
                  회원가입
                </Button>
              </Link>
            </>
          }
        />
        <Inner>
          <Title>회원가입</Title>
          <RegistForm />
          <Guide>
            이미 계정이 있으신가요?
            <Link href="/auth/login">
              <Button
                justifycontent="center"
                isoutlined={true}
                border="none"
                size="large"
              >
                로그인하기
              </Button>
            </Link>
          </Guide>
        </Inner>
      </MainLayout>
    </>
  );
}
