import { Header, MainLayout } from '@/components/Layout';
import Head from 'next/head';
import { Inner } from '@/styles/pageStyles/chat/index.style';
import { Chats, chatSlice, getChatRooms } from '@/features/chats';

import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useRouter } from 'next/router';

export default function MyChats() {
  const dispatch = useDispatch();
  const router = useRouter();
  const { userUuid } = useSelector(({ auth }) => auth);
  useEffect(() => {
    if (!userUuid) {
      router.push('/auth/login');
      return;
    }
    (async () => {
      try {
        const result = await getChatRooms();
        console.log(result);
        dispatch(chatSlice.actions.setChatRooms(result.data));
      } catch (error) {
        console.error(error);
      }
    })();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header title="내 채팅목록" />
        <Inner>
          <Chats />
        </Inner>
      </MainLayout>
    </>
  );
}
