import { Header, MainLayout } from '@/components/Layout';
import Head from 'next/head';
import { Inner } from './index.style';
import { Chats } from '@/features/chats';
import { ChatProps } from '@/features/chats/components/Chat';

import k8s from '@/assets/images/k8s.png';

export default function Chat() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header title="내 채팅목록" />
        <Inner>
          <Chats chats={chats} />
        </Inner>
      </MainLayout>
    </>
  );
}

const emptyChats: ChatProps[] = [];

const chats: ChatProps[] = [
  {
    id: '1',
    userImage: k8s.src,
    nickname: '김재만',
    recentChatedAt: '2023-12-19',
    recentMessage:
      '도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요',
    unconfirmedMessageNumber: 0,
  },
  {
    id: '2',
    nickname: '김재만',
    recentChatedAt: '2023-12-19',
    recentMessage:
      '도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요',
    unconfirmedMessageNumber: 5,
  },
  {
    id: '3',
    userImage: k8s.src,
    nickname: '김재만',
    recentChatedAt: '2023-12-19',
    recentMessage:
      '도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요',
    unconfirmedMessageNumber: 999,
  },
  {
    id: '4',
    nickname: '김재만',
    recentChatedAt: '2023-12-19',
    recentMessage:
      '도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요',
    unconfirmedMessageNumber: 0,
  },
  {
    id: '5',
    nickname: '김재만',
    recentChatedAt: '2023-12-19',
    recentMessage:
      '도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요',
    unconfirmedMessageNumber: 0,
  },
  {
    id: '6',
    nickname: '김재만',
    recentChatedAt: '2023-12-19',
    recentMessage:
      '도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요',
    unconfirmedMessageNumber: 5,
  },
  {
    id: '7',
    nickname: '김재만',
    recentChatedAt: '2023-12-19',
    recentMessage:
      '도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요',
    unconfirmedMessageNumber: 999,
  },
  {
    id: '8',
    nickname: '김재만',
    recentChatedAt: '2023-12-19',
    recentMessage:
      '도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요',
    unconfirmedMessageNumber: 0,
  },
  {
    id: '9',
    nickname: '김재만',
    recentChatedAt: '2023-12-19',
    recentMessage:
      '도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요',
    unconfirmedMessageNumber: 0,
  },
  {
    id: '10',
    nickname: '김재만',
    recentChatedAt: '2023-12-19',
    recentMessage:
      '도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요',
    unconfirmedMessageNumber: 5,
  },
  {
    id: '11',
    nickname: '김재만',
    recentChatedAt: '2023-12-19',
    recentMessage:
      '도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요 도와주세요',
    unconfirmedMessageNumber: 999,
  },
];
