import { Button } from '@/components/Elements';
import { Header, MainLayout } from '@/components/Layout';
import Head from 'next/head';
import Link from 'next/link';
import {
  Buttons,
  Email,
  Infomations,
  Inner,
  Nickname,
  Profile,
  RequestState,
  Requests,
  TextInfomations,
  UserImage,
} from './index.style';

import k8s from '@/assets/images/k8s.png';
import NoProfileUser from '@/assets/icons/no-profile-user.svg';
import { useState } from 'react';
import { DeleteAccount, Logout } from '@/features/auth';
import { VerticalPost } from '@/features/posts';
import { VerticalUser } from '@/features/users';
import {
  CancelMentoringRequest,
  RecieveMentoring,
} from '@/features/mentorings';

export default function MyPage() {
  const [selectedList, setSelectedList] = useState('sended');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header title="마이페이지" rightbuttons={<></>} />
        <Inner>
          <Profile>
            <Infomations>
              <UserImage src={NoProfileUser.src} />
              <TextInfomations>
                <Nickname>김재만</Nickname>
                <Email>daga4242@gmail.com</Email>
              </TextInfomations>
            </Infomations>
            <Link href="/my-page/profile">
              <Button>프로필 보기</Button>
            </Link>
          </Profile>
          <Buttons>
            <Button
              isoutlined={selectedList === 'sended' ? false : true}
              onclick={() => setSelectedList('sended')}
              justifycontent="center"
            >
              보낸 멘토링 신청
            </Button>
            <Button
              isoutlined={selectedList === 'sended' ? true : false}
              onclick={() => setSelectedList('received')}
              justifycontent="center"
            >
              받은 멘토링 신청
            </Button>
          </Buttons>
          <Requests>
            {selectedList === 'sended'
              ? sendedRequests.map((post, i) => (
                  <CancelMentoringRequest
                    key={i}
                    id={post.id}
                    triggerButton={
                      <VerticalPost
                        id={post.id}
                        title={post.title}
                        image={post.image}
                        skill={post.skill}
                        region={post.region}
                        rightElement={
                          <RequestState>{post.status}</RequestState>
                        }
                      />
                    }
                  />
                ))
              : receivedRequests.map((user, i) => (
                  <RecieveMentoring
                    key={i}
                    id={user.id}
                    triggerButton={
                      <VerticalUser
                        nickname={user.nickname}
                        image={user.image}
                        skill={user.skill}
                        region={user.region}
                        rightElement={
                          <RequestState>{user.status}</RequestState>
                        }
                      />
                    }
                  />
                ))}
          </Requests>
          <Buttons>
            <Logout />
            <DeleteAccount />
          </Buttons>
        </Inner>
      </MainLayout>
    </>
  );
}

const sendedRequests = [
  {
    id: '1',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
    status: '수락 대기 중',
  },
  {
    id: '2',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
    status: '수락 대기 중',
  },
  {
    id: '3',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
    status: '수락 대기 중',
  },
  {
    id: '4',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
    status: '수락 대기 중',
  },
  {
    id: '5',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
    status: '수락 대기 중',
  },
  {
    id: '6',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
    status: '수락 대기 중',
  },
];

const receivedRequests = [
  {
    id: '1',
    image: NoProfileUser.src,
    nickname: '김재만',
    skill: 'React',
    region: '동작구',
    status: '수락 대기 중',
  },
  {
    id: '2',
    image: NoProfileUser.src,
    nickname: '김재만',
    skill: 'React',
    region: '동작구',
    status: '수락 대기 중',
  },
  {
    id: '3',
    image: NoProfileUser.src,
    nickname: '김재만',
    skill: 'React',
    region: '동작구',
    status: '수락 대기 중',
  },
  {
    id: '4',
    image: NoProfileUser.src,
    nickname: '김재만',
    skill: 'React',
    region: '동작구',
    status: '수락 대기 중',
  },
  {
    id: '5',
    image: NoProfileUser.src,
    nickname: '김재만',
    skill: 'React',
    region: '동작구',
    status: '수락 대기 중',
  },
];
