import Head from 'next/head';
import { Header, MainLayout } from '@/components/Layout';
import { Button } from '@/components/Elements';
import { useRouter } from 'next/router';

import { FaArrowLeft } from 'react-icons/fa';
import { Buttons, Inner } from '@/styles/pageStyles/my-page/profile.style';
import { useEffect, useState } from 'react';
import { Profile } from '@/features/users';
import { UserPosts, VerticalPostProps } from '@/features/posts';

import k8s from '@/assets/images/k8s.png';
import { MyMentorings } from '@/features/mentorings';
import { MentoringProps } from '@/features/mentorings/components/Mentoring';
import { useSearchParams } from 'next/navigation';
import { useSelector } from 'react-redux';

export default function MyProfile() {
  const [selectedTap, setSelectedTap] = useState('profile');
  const searchParams = useSearchParams();

  const tap = searchParams.get('tap');
  useEffect(() => {
    if (tap === 'mentoring') {
      setSelectedTap('mentoring');
    }
  }, [tap]);
  const router = useRouter();

  const userUuid = useSelector(({ auth }) => auth.userUuid);
  useEffect(() => {
    if (!userUuid) {
      router.push('/');
    }
  }, [userUuid]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header
          title="내 프로필"
          leftbuttons={
            <Button
              textstyle="title"
              size="large"
              variant="background"
              padding="2px"
              startIcon={<FaArrowLeft />}
              onclick={() => router.back()}
            />
          }
        />
        <Inner>
          <Buttons>
            <Button
              isoutlined={selectedTap === 'profile' ? false : true}
              justifycontent="center"
              onclick={() => setSelectedTap('profile')}
            >
              내 프로필
            </Button>
            <Button
              isoutlined={selectedTap === 'post' ? false : true}
              justifycontent="center"
              onclick={() => setSelectedTap('post')}
            >
              게시물 목록
            </Button>
            <Button
              isoutlined={selectedTap === 'mentoring' ? false : true}
              justifycontent="center"
              onclick={() => setSelectedTap('mentoring')}
            >
              멘토링 목록
            </Button>
          </Buttons>
          {selectedTap === 'profile' ? (
            <Profile />
          ) : selectedTap === 'post' ? (
            <UserPosts
              postsAsMentor={postsAsMentor}
              postsAsMentee={postsAsMentee}
            />
          ) : (
            <MyMentorings
              mentoringsAsMentor={mentoringsAsMentor}
              mentoringsAsMentee={mentoringsAsMentee}
            />
          )}
        </Inner>
      </MainLayout>
    </>
  );
}

const postsAsMentor: VerticalPostProps[] = [];

const postsAsMentee: VerticalPostProps[] = [
  {
    id: '1',
    image: k8s.src,
    title: '멘토 급구! ',
    skill: 'React',
    region: '동작구',
  },
  {
    id: '2',
    image: null,
    title: '멘토 급구! ',
    skill: 'React',
    region: '동작구',
  },
  {
    id: '3',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
  },
  {
    id: '4',
    image: null,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
  },
  {
    id: '5',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
  },
  {
    id: '6',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
  },
  {
    id: '7',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
  },
  {
    id: '8',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
  },
  {
    id: '9',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
  },
  {
    id: '10',
    image: k8s.src,
    title: '멘토 급구! 멘토멘토',
    skill: 'React',
    region: '동작구',
  },
];

const mentoringsAsMentor: MentoringProps[] = [];

const mentoringsAsMentee: MentoringProps[] = [
  {
    id: '1',
    title: '동작구 멘토 구합니다',
    promisedAt: '2023-12-19',
    region: '서울특별시 동작구 노량진동',
    status: '완료',
  },
  {
    id: '2',
    title: '동작구 멘토 구합니다',
    promisedAt: '2023-12-19',
    region: '서울특별시 동작구 노량진동',
    status: '완료',
  },
  {
    id: '3',
    title: '동작구 멘토 구합니다',
    promisedAt: '2023-12-19',
    region: '서울특별시 동작구 노량진동',
    status: '완료',
  },
  {
    id: '4',
    title: '동작구 멘토 구합니다',
    promisedAt: '2023-12-19',
    region: '서울특별시 동작구 노량진동',
    status: '완료',
  },
  {
    id: '5',
    title: '동작구 멘토 구합니다',
    promisedAt: '2023-12-19',
    region: '서울특별시 동작구 노량진동',
    status: '완료',
  },
  {
    id: '6',
    title: '동작구 멘토 구합니다',
    promisedAt: '2023-12-19',
    region: '서울특별시 동작구 노량진동',
    status: '완료',
  },
  {
    id: '7',
    title: '동작구 멘토 구합니다',
    promisedAt: '2023-12-19',
    region: '서울특별시 동작구 노량진동',
    status: '완료',
  },
  {
    id: '8',
    title: '동작구 멘토 구합니다',
    promisedAt: '2023-12-19',
    region: '서울특별시 동작구 노량진동',
    status: '완료',
  },
  {
    id: '9',
    title: '동작구 멘토 구합니다',
    promisedAt: '2023-12-19',
    region: '서울특별시 동작구 노량진동',
    status: '완료',
  },
  {
    id: '10',
    title: '동작구 멘토 구합니다',
    promisedAt: '2023-12-19',
    region: '서울특별시 동작구 노량진동',
    status: '완료',
  },
  {
    id: '11',
    title: '동작구 멘토 구합니다',
    promisedAt: '2023-12-19',
    region: '서울특별시 동작구 노량진동',
    status: '완료',
  },
];
