import Head from 'next/head';
import { Header, MainLayout } from '@/components/Layout';
import { Button } from '@/components/Elements';
import { useRouter } from 'next/router';

import { FaArrowLeft } from 'react-icons/fa';
import { Buttons, Inner } from './profile.style';
import { useState } from 'react';
import { Profile } from '@/features/users';

export default function MyProfile() {
  const [selectedTap, setSelectedTap] = useState('profile');
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header
          title="내 프로필"
          leftbuttons={
            <Button
              textstyle="title"
              size="large"
              variant="background"
              padding="2px"
              startIcon={<FaArrowLeft />}
              onclick={() => router.back()}
            />
          }
        />
        <Inner>
          <Buttons>
            <Button
              isoutlined={selectedTap === 'profile' ? false : true}
              justifycontent="center"
              onclick={() => setSelectedTap('profile')}
            >
              내 프로필
            </Button>
            <Button
              isoutlined={selectedTap === 'postlist' ? false : true}
              justifycontent="center"
              onclick={() => setSelectedTap('postlist')}
            >
              게시물 목록
            </Button>
            <Button
              isoutlined={selectedTap === 'mentorings' ? false : true}
              justifycontent="center"
              onclick={() => setSelectedTap('mentorings')}
            >
              멘토링 목록
            </Button>
          </Buttons>
          {selectedTap === 'profile' ? <Profile /> : <></>}
        </Inner>
      </MainLayout>
    </>
  );
}
