import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Button, Slider } from '@/components/Elements';
import { MainLayout } from '@/components/Layout';
import { Post } from '@/features/posts';
import { User } from '@/features/users';
import { PostSeeAll, PostSeeAllContent, UserSeeAll } from './index.style';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Slider title="추천 멘토 게시물" link="/posts">
          <>
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Link href="/posts">
              <PostSeeAll>추천멘토 게시물 모두 보기</PostSeeAll>
            </Link>
          </>
        </Slider>
        <Slider title="추천 멘티 게시물" link="/posts">
          <>
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Post />
            <Link href="/posts">
              <PostSeeAll>추천멘티 게시물 모두 보기</PostSeeAll>
            </Link>
          </>
        </Slider>
        <Slider title="추천 멘토" link="/users">
          <>
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <Link href="/users">
              <UserSeeAll>추천 멘토 모두 보기</UserSeeAll>
            </Link>
          </>
        </Slider>
        <Slider title="추천 멘티" link="/user">
          <>
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <User />
            <Link href="/users">
              <UserSeeAll>추천 멘티 모두 보기</UserSeeAll>
            </Link>
          </>
        </Slider>
      </MainLayout>
    </>
  );
}
{
  /* <main className={`${styles.main} ${inter.className}`}></main> */
}
