import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Button, Slider } from '@/components/Elements';
import { Header, MainLayout } from '@/components/Layout';
import { HorizontalPost, WritePost } from '@/features/posts';
import { User } from '@/features/users';
import { Inner, PostSeeAll, UserSeeAll } from './index.style';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header
          rightbuttons={
            <>
              <Link href="/auth/login">
                <Button>로그인</Button>
              </Link>
              <Link href="/auth/regist">
                <Button variant="primary" isoutlined={true}>
                  회원가입
                </Button>
              </Link>
            </>
          }
        />
        <Inner>
          <Slider title="추천 멘토 게시물" link="/search?list=posts">
            <>
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <Link href="/post">
                <PostSeeAll>추천멘토 게시물 모두 보기</PostSeeAll>
              </Link>
            </>
          </Slider>
          <Slider title="추천 멘티 게시물" link="/search?list=users">
            <>
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <HorizontalPost />
              <Link href="/post">
                <PostSeeAll>추천멘티 게시물 모두 보기</PostSeeAll>
              </Link>
            </>
          </Slider>
          <Slider title="추천 멘토" link="/search?list=users">
            <>
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <Link href="/users">
                <UserSeeAll>추천 멘토 모두 보기</UserSeeAll>
              </Link>
            </>
          </Slider>
          <Slider title="추천 멘티" link="/user">
            <>
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <User />
              <Link href="/users">
                <UserSeeAll>추천 멘티 모두 보기</UserSeeAll>
              </Link>
            </>
          </Slider>
        </Inner>
      </MainLayout>
      <WritePost />
    </>
  );
}
{
  /* <main className={`${styles.main} ${inter.className}`}></main> */
}
