import { Button } from '@/components/Elements';
import { Header, MainLayout } from '@/components/Layout';
import { PostForm } from '@/features/posts/components/PostForm';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { FaArrowLeft } from 'react-icons/fa';
import { Inner } from '@/styles/pageStyles/post/edit.style';

export default function Write() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header
          title="게시물 수정하기"
          leftbuttons={
            <Button
              textstyle="title"
              size="large"
              variant="background"
              padding="2px"
              startIcon={<FaArrowLeft />}
              onclick={() => router.back()}
            />
          }
          rightbuttons={
            <Button form="post-form" type="submit">
              수정완료
            </Button>
          }
        />
        <Inner>
          <PostForm />
        </Inner>
      </MainLayout>
    </>
  );
}
