// import { Spinner } from '@/components/Elements';
import { MainLayout } from '@/components/Layout';
import Head from 'next/head';
import {
  Waitting,
  WaittingText,
} from '@/styles/pageStyles/auto-match/index.style';

export default function AutoMatch() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Waitting>
          <WaittingText>자동매칭이 진행 중입니다</WaittingText>
          <WaittingText>잠시만 기다려주세요</WaittingText>
          {/* <Spinner /> */}
        </Waitting>
      </MainLayout>
    </>
  );
}
